### ISSUE TITLE
New/Update ticket problem.

### ISSUE THREAD

**Issue by lubomirsb** [N3XT0R/ZF2-OTRS#1]
When creating a ticket you can set the id of the queue but not the name. 
$oTicket->setQueue('Postmaster'); -> not working.
$oTicket->setQueueID(1); -> working (1 is the postmaster queue)

**Comment by N3XT0R** [comment]
Found the bug inside the sourcecode and fixed it. Please try again.

**Comment by lubomirsb** [comment]
Works fine now. Thank you !
